language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
- iojs
after_success: npm run coveralls
env:
  global:
    secure: uNf+J6/NcMOs/c0vnOb1qK+HSf5deNOnqTvGE3EVC9U6iYBxc6Fo5pD0c4vb2d+B8eXOkg4wEDAZ15fFjcF19ebhTHvD7wviROpcQ1waMs+r2LqMHeMX41iJC88F0+jwt07OepufvlzNtM3B+nedCQBMu4JqXzs05kgN+2JWAEpRehtKEUezvRDweL0cRGtTfinQyfGeqxqJvOISH8KxMfIbF3dAQhQY0s5jqI7Ezn0zJ+lHWscSVpuVdesyKztwgneAO3fVYIUnxg95WaW/Va0Rd2sEYZz815OsquJWpq6dNwi6N10kdcN/jWCiSnSixCtPaXde/UcyxpKIFyDRrnu6AmQS/dcLcJjrDzg73HX+/FAovxMDje3D5sxEwnIOaDAJFn9nDohBrt320zW5RgorgVIkOnU9nK0u3+n02j/WZq7enJT5W/U957oxkUpaS4GkdkTqnXhyMG+EB34kXiKTQtEiNSP9aICZfBrXm3Tekee2JEMRhyWhd2lVPJXMXa+DJcsXYRhT65zW/SO4XXziTmkvJbV0BPTaUq9wNXo36PML0DH5vlwQu6kpb/3UdC3RO5H5mubOn07I8TgALtN+Cn2vpoJPtrk3wG3JpdmBmM6ODqq0+nqbfxDqRsr33yqeRIx+QAYtmf76RwnwrVUvo24zkzLkrgsG1Hl7Mbs=
